server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/RansaraNawarathne/spring-cloud-config-store
          uri: https://github.com/RansaraNawarathne/rent-cloud-config-store
          search-paths:
            - 'service-config/*service'

#          username: RansaraNawarathne
#          password: 12345678
