server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/RansaraNawarathne/spring-cloud-config-store.git
          uri: https://github.com/RansaraNawarathne/rent-cloud-config-store
          search-paths:
            - 'service-config/*service'
#          If the repository private provide username and the password
#          username: Admin
#          password: test112233
#          Adding search directories to avoid getting global default configuration